BEM VINDO A MEU PERFIL

MEU NOME E EDUARDO

ESTOU ESTUDANDO,
ESTOU ME DESSEVOLVEDO NA LINGUAGUEM JAVASCRIPT

SE VOCÊ QUISER ENTRAR EM CONTATO COMIGO⬇️

00001109223250SP@AL.EDUCACAO.SP.GOV.BR

![](https://media1.tenor.com/m/YU7xce8F7goAAAAd/r9-ronaldo-nazario.gif)
